const studentsFormOptions={
    model:{
        id:'',
        name:'',
        sex:'',
        class:''
    },
    labelWidth : '120px',
    itemList: [
        {
            name:'学号',
            type:'my-input',
            option:{
                type:'text',
                value:'',
                placeholder:'请输入学号',
                style:{
                    width:'200px',
                }
            }
        },
        {
            name:'姓名',
            type:'my-input',
            option:{
                type:'text',
                value:'',
                placeholder:'请输入姓名',
                style:{
                    width:'200px',
                }
            }
        },
        {
            name:'性别',
            type:'my-radio',
            option:{
                value:'',
                border:true,
                itemList:[
                    {
                        label:'男',
                        text:'男'
                    },
                    {
                        label:'女',
                        text:'女'
                    },
                ]
            }
        },
        {
            name:'班级',
            type:'my-input',
            option:{
                type:'text',
                value:'',
                placeholder:'请输入班级',
                style:{
                    width:'200px',
                }
            }
        },
    ]
}
export default studentsFormOptions
