const studentsOptions=[
    {
        id:'00001',
        name:'王一',
        sex:'男',
        class:'1901',
    },
    {
        id:'00001',
        name:'王二',
        sex:'男',
        class:'1901',
    },
    {
        id:'00001',
        name:'王三',
        sex:'男',
        class:'1902',
    },
    {
        id:'00001',
        name:'王四',
        sex:'男',
        class:'1903',
    },
    {
        id:'00001',
        name:'王五',
        sex:'男',
        class:'1901',
    },
    {
        id:'00001',
        name:'王六',
        sex:'男',
        class:'1901',
    },
    {
        id:'00001',
        name:'王一',
        sex:'男',
        class:'1901',
    },
    {
        id:'00001',
        name:'王一',
        sex:'男',
        class:'1901',
    },
]
export default studentsOptions
