const studentsFormOptions={
    model:{
        id:'',
        name:'',
        sex:'',
        class:''
    },
    labelWidth : '120px',
    itemList: [
        {
            name:'id',
            type:'my-input',
            option:{
                name:'id',
                type:'text',
                value:'',
                placeholder:'请输入学号',
                style:{
                    width:'200px',
                }
            }
        },
        {
            name:'name',
            type:'my-input',
            option:{
                name:'name',
                type:'text',
                value:'',
                placeholder:'请输入姓名',
                style:{
                    width:'200px',
                }
            }
        },
        {
            name:'sex',
            type:'my-radio',
            option:{
                name:'sex',
                value:'',
                border:true,
                itemList:[
                    {
                        label:'男',
                        text:'男'
                    },
                    {
                        label:'女',
                        text:'女'
                    },
                ]
            }
        },
        {
            name:'class',
            type:'my-input',
            option:{
                name:'class',
                type:'text',
                value:'',
                placeholder:'请输入班级',
                style:{
                    width:'200px',
                }
            }
        },
    ]
}
export default studentsFormOptions
